[package]
name = "bsrs"
version = "0.1.0"
edition = "2021"
build = "scripts/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.96"

[build-dependencies]
serde_json = "1.0.96"
